import Link from 'next/link';
import type { Metadata } from 'next';

import { BASE_URL } from '@/lib/config';
import { Badge, Card, CardBody, CardHeader } from '@/components/ui/primitives';
import { ActionForm, Field, TextArea, TextInput } from '@/components/shared/ActionForm';
import { ProvenanceBadge } from '@/components/shared/badges';
import { GeneratedArt } from '@/components/shared/GeneratedArt';
import { getBusiness, getLandingPagesForBusiness } from '@/server/data/repository';
import {
  generateBusinessLandingPageForm,
  publishBusinessLandingPageForm,
  updateBusinessLandingPageForm,
} from '@/server/actions/forms';
import { addGalleryMedia, removeGalleryMedia, enhanceGalleryImage, enhanceHeroImage, uploadHeroImage } from '@/server/actions/landing-pages';
import { MediaGalleryUploader } from '@/components/shared/MediaGalleryUploader';
import { requirePartner } from '@/server/auth/session';
import { HeroImageUploader } from '@/components/shared/HeroImageUploader';

export const metadata: Metadata = { title: 'Your landing page' };
export const dynamic = 'force-dynamic';

const sectionBody = (page: { sections: { key: string; body: string }[] }, key: string): string =>
  page.sections.find((section) => section.key === key)?.body ?? '';

export default async function PartnerLandingPagePage() {
  const { businessId } = await requirePartner();
  const business = getBusiness(businessId);
  const page = getLandingPagesForBusiness(businessId)[0];

  return (
    <div className="mx-auto max-w-3xl space-y-5">
      <div>
        <h1 className="text-[22px] font-semibold tracking-tight text-ink-900">Your landing page</h1>
        <p className="mt-1 text-[13px] text-ink-600">
          A one-page site for {business?.name ?? 'your business'}, drafted with AI from your listing and
          published with a link you can share anywhere.
        </p>
      </div>

      {!page ? (
        <Card>
          <CardHeader title="Generate your page" subtitle="Content and a hero image, drafted in a few seconds." />
          <CardBody>
            <ActionForm action={generateBusinessLandingPageForm} submitLabel="Generate with AI" pendingLabel="Generating…" />
          </CardBody>
        </Card>
      ) : (
        <>
          <Card>
            <CardHeader
              title="Preview"
              action={
                <Badge tone={page.status === 'PUBLISHED' ? 'good' : 'neutral'}>
                  {page.status === 'PUBLISHED' ? 'Published' : 'Draft'}
                </Badge>
              }
            />
            <CardBody className="space-y-3">
              <GeneratedArt
                seed={page.slug}
                label={page.title}
                imageUrl={page.heroImageUrl}
                height="md"
                className="rounded-md"
              />
              <HeroImageUploader 
                pageId={page.id} 
                hasHeroImage={!!page.heroImageUrl} 
                onEnhance={enhanceHeroImage} 
                onUpload={uploadHeroImage}
              />
              <div className="flex flex-wrap items-center gap-2">
                <ProvenanceBadge provenance={page.provenance} />
                <span className="text-[12px] text-ink-500">Generated by {page.generatedBy}</span>
              </div>
              <div className="flex flex-wrap items-center gap-3">
                <ActionForm
                  action={publishBusinessLandingPageForm}
                  submitLabel={page.status === 'PUBLISHED' ? 'Unpublish' : 'Publish'}
                  pendingLabel="Saving…"
                  variant={page.status === 'PUBLISHED' ? 'secondary' : 'primary'}
                  size="sm"
                  hiddenFields={{ published: page.status === 'PUBLISHED' ? 'false' : 'true' }}
                />
                {page.status === 'PUBLISHED' ? (
                  <Link
                    href={`/p/${page.slug}`}
                    target="_blank"
                    className="text-[12px] font-medium text-brand-700 underline"
                  >
                    {BASE_URL}/p/{page.slug} ↗
                  </Link>
                ) : (
                  <span className="text-[12px] text-ink-500">Publish to get a shareable link.</span>
                )}
              </div>
            </CardBody>
          </Card>

          <Card>
            <CardHeader
              title="Edit content"
              subtitle="Change anything below, or regenerate the whole page with AI."
              action={
                <ActionForm
                  action={generateBusinessLandingPageForm}
                  submitLabel="Regenerate with AI"
                  pendingLabel="Generating…"
                  variant="secondary"
                  size="sm"
                />
              }
            />
            <CardBody>
              <ActionForm action={updateBusinessLandingPageForm} submitLabel="Save changes" pendingLabel="Saving…">
                <div className="grid gap-4 sm:grid-cols-2">
                  <Field label="Title" name="title" required>
                    <TextInput id="title" name="title" defaultValue={page.title} maxLength={120} required />
                  </Field>
                  <Field label="Tagline" name="tagline" required>
                    <TextInput id="tagline" name="tagline" defaultValue={page.tagline} maxLength={200} required />
                  </Field>
                  <div className="sm:col-span-2">
                    <Field label="About" name="about" required>
                      <TextArea id="about" name="about" defaultValue={sectionBody(page, 'about')} maxLength={1200} required />
                    </Field>
                  </div>
                  <div className="sm:col-span-2">
                    <Field
                      label="What guests can expect"
                      name="highlights"
                      hint="One per line."
                    >
                      <TextArea
                        id="highlights"
                        name="highlights"
                        defaultValue={sectionBody(page, 'highlights')}
                        maxLength={1200}
                      />
                    </Field>
                  </div>
                  <div className="sm:col-span-2">
                    <Field label="Good to know" name="practical" hint="One per line.">
                      <TextArea
                        id="practical"
                        name="practical"
                        defaultValue={sectionBody(page, 'practical')}
                        maxLength={1200}
                      />
                    </Field>
                  </div>
                  <div className="sm:col-span-2">
                    <Field
                      label="Booking link (optional)"
                      name="bookingUrl"
                      hint="Leave blank to send visitors to enquire on mTour Agent."
                    >
                      <TextInput
                        id="bookingUrl"
                        name="bookingUrl"
                        defaultValue={page.bookingUrl ?? ''}
                        placeholder="https://…"
                      />
                    </Field>
                  </div>
                </div>
              </ActionForm>
            </CardBody>
          </Card>
          
          <Card>
            <CardBody className="pt-4">
              <MediaGalleryUploader
                pageId={page.id}
                media={page.galleryMedia}
                onAdd={addGalleryMedia}
                onRemove={removeGalleryMedia}
                onEnhance={enhanceGalleryImage}
              />
            </CardBody>
          </Card>
        </>
      )}
    </div>
  );
}
