-- AlterTable
ALTER TABLE `CampaignMetric` MODIFY `metric` ENUM('VIEWS', 'WATCH_TIME', 'CLICKS', 'DESTINATION_PAGE_VISITS', 'ITINERARY_ADDS', 'CHECKINS', 'BOOKINGS', 'PAID_BOOKINGS') NOT NULL;

-- AlterTable
ALTER TABLE `Refund` MODIFY `providerRefundId` VARCHAR(64) NULL;
